version: "3.9"

services:

  postgres:
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_DB: demo_db
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/database.sql:/docker-entrypoint-initdb.d/database.sql
    ports:
      - "5433:5432"

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  tileserver:
    image: maptiler/tileserver-gl
    volumes:
      - ./tiles:/data
    ports:
      - "8081:8080"

volumes:
  pgdata:


# version: "3.9"

# services:
#   postgres:
#     image: postgres:15
#     container_name: postgres_db
#     restart: always
#     environment:
#       POSTGRES_DB: demo_db
#       POSTGRES_USER: demo_user
#       POSTGRES_PASSWORD: demo_pass
#     ports:
#       - "5433:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

#   springboot:
#     build: .
#     container_name: spring_app
#     depends_on:
#       - postgres
#     ports:
#       - "8080:8080"
#     volumes:
#       - .:/app
#     environment:
#       SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/demo_db
#       SPRING_DATASOURCE_USERNAME: demo_user
#       SPRING_DATASOURCE_PASSWORD: demo_pass

# volumes:
#   postgres_data:
